properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
        timestamps()
    }

    stages {

        stage("Build") {
            steps {
                sh "podman build -t vkapi --file project/dockerfiles/vkapi/Dockerfile project/vkapi"
                sh "podman build -t myapp --file project/dockerfiles/myapp/Dockerfile project/dockerfiles/myapp"
                dir('project') {
                    sh "poetry install"
                }
            }
        }

        stage("Run environment") {
            environment {
                VK_API_TOKEN = credentials('27a5cd39-a350-4721-b2da-9d8ecaea8fcc')
            }
            steps {
                // todo different pod name for each run
                sh "podman pod stop qa-project || true"
                sh "podman pod rm qa-project || true"
                sh "podman pod create --name qa-project"

                // todo credentials to jenkins creds
                sh "podman run -d --pod qa-project --name qamysql -e MYSQL_DATABASE=technoatom -e MYSQL_USER=test_qa -e MYSQL_PASSWORD=qa_test -e MYSQL_ROOT_PASSWORD=root -v qa-mysql-volume:/var/lib/mysql mysql"
                sh "podman run -d --pod qa-project --name myapp myapp"
                sh "podman run -d --pod qa-project --name vkapi -e VK_API_TOKEN=$VK_API_TOKEN vkapi"
            }
        }

        stage("Testing") {
            environment {
                VK_API_TOKEN = credentials('27a5cd39-a350-4721-b2da-9d8ecaea8fcc')
            }
            steps {
                dir('project') {
                    sh "PYTHONPATH=vkapi poetry run python -m pytest -s --alluredir=allure-results"
                }
            }
        }

        stage("Cleanup") {
            steps {
                sh "podman pod stop qa-project"
                sh "podman pod rm qa-project"
            }
        }
    }

    post {
        always {
            allure([
                reportBuildPolicy: 'ALWAYS',
                results: [[path: '$WORKSPACE/allure-results']]
            ])
        }
    }
}